#spring:
#  application:
#    name: xi11a-api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#        lower-case-service-id: true

#eureka:
#  instance:
#    hostname: localhost
#    instanceId: prod

#server:
#  port: 8765